# App Info
name = "vc-consultant app"
client_id = "1844b97873b270b025334fd34790185c"
application_url = "https://relevant-call-theoretical-structured.trycloudflare.com" # backend URL
embedded = true
handle = "label-node"

[access_scopes]
scopes = "read_customers,write_customers,write_draft_orders,read_orders,write_orders"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://test-online-consultation.zend-apps.com/app/callback"
]

[webhooks]
api_version = "2025-10"



[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://test-online-consultation.zend-apps.com/api/webhooks/webhooks"
 
# App Proxy configuration
[app_proxy]
prefix = "apps"                # The Shopify prefix, usually 'apps'
subpath = "consultant-theme"   # The subpath for your app proxy
url = "https://test-online-consultation.zend-apps.com/app/consultant-theme"  # Your backend endpoint
