# App basic info
client_id = "YOUR_CLIENT_ID_FROM_PARTNER_DASHBOARD"
name = "vc-consultant app"
handle = "label-node"
embedded = true

# App URL (Embedded UI)
application_url = "https://fitness-modem-sudden-funeral.trycloudflare.com"

# OAuth / Auth
[auth]
redirect_urls = [
  "https://test-online-consultation.zend-apps.com/app/callback"
]

# Access scopes
[access_scopes]
scopes = "read_customers,write_customers,write_draft_orders,read_orders,write_orders"
optional_scopes = []
use_legacy_install_flow = false

# App Proxy
[app_proxy]
prefix = "apps"
subpath = "consultant-theme"
url = "https://test-online-consultation.zend-apps.com/app/consultant-theme"

# Webhooks (VERY IMPORTANT FOR REVIEW)
[webhooks]
api_version = "2024-07"

[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]
uri = "https://test-consultation-app.zend-apps.com/api/webhooks"
